import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/component/navBar";
import Footer from "@/component/Footer";
import InquiryForm from "@/component/main/InquiryForm";
import ChatWidget from "@/component/main/ChatWidget";
import Footer1 from "@/component/Footer1";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* Navbar */}
        <div className="top-0 left-1/2 z-[100] absolute -translate-x-1/2 w-full max-w-[1400px] px-10 py-5 fixed">
          <NavBar />
        </div>

        {/* Page Content */}
        <main className="flex-grow ">{children}</main>

        {/* Footer */}
        {/* <Footer /> */}
        <Footer1 />
        <InquiryForm />
        <ChatWidget />
      </body>
    </html>
  );
}
